### ISSUE TITLE
not response for the clone button?

### ISSUE THREAD

**Issue by liamxg** [nicfel/Reassortment-Tutorial#3]
Dear @tgvaughan,

I find that the button is not response when I click the `OK` ? Please see below:

<img width="540" alt="image" src="https://github.com/nicfel/Reassortment-Tutorial/assets/46078579/8321113d-f435-4f8c-9a89-b3832a1d1b17">

**Comment by tgvaughan** [comment]
@nicfel ?

**Comment by liamxg** [comment]
Dear @tgvaughan,

I updated to 2.7.6, and it works, but for 2.6.7, not work.
